# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebe236c18465cf5f1d39db79baa4b27c4b97b0653827da0015fa58ef6c02797078c5de1400237725ac177c32d14447adc385b6c0a28088461493b4fb577455c1

test:
  secret_key_base: 573c60966dcfabd2e61cb7afd216f93306f87669b5c4b8197f15d8193ccbd48953dba19ce79070e61e5270042abcf31c918836e63a12b6e5be4bef7b394c12d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
